import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Container from "@/components/Container/Container";

const clashDisplay = localFont({
  src: "./fonts/ClashDisplay-Variable.woff",
  variable: "--font-clash-display",
  weight: "100 900",
});

const clashDisplay2 = localFont({
  src: "./fonts/ClashDisplay-Variable.woff2",
  variable: "--font-clash-display",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} ${clashDisplay2.className}`}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
